/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : IDL.Nat,
  'number' : IDL.Nat,
});
export const PlaylistItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'playlistId' : IDL.Nat,
  'notes' : IDL.Text,
  'resourceUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const Playlist = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'chapterId' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createPlaylist' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'createPlaylistItem' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'generatePlaylistFromTelegram' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getItemsByPlaylist' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PlaylistItem)],
      ['query'],
    ),
  'getPlaylistsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Playlist)], ['query']),
  'markItemStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'searchPlaylistsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Playlist)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : IDL.Nat,
    'number' : IDL.Nat,
  });
  const PlaylistItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'playlistId' : IDL.Nat,
    'notes' : IDL.Text,
    'resourceUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const Playlist = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'chapterId' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createPlaylist' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'createPlaylistItem' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'generatePlaylistFromTelegram' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getItemsByPlaylist' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PlaylistItem)],
        ['query'],
      ),
    'getPlaylistsByChapter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'markItemStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'searchPlaylistsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };