/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'subjectId' : bigint,
  'number' : bigint,
}
export interface Playlist {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'chapterId' : bigint,
}
export interface PlaylistItem {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'order' : bigint,
  'description' : string,
  'playlistId' : bigint,
  'notes' : string,
  'resourceUrl' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createChapter' : ActorMethod<
    [bigint, bigint, string, bigint, string],
    undefined
  >,
  'createPlaylist' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'createPlaylistItem' : ActorMethod<
    [bigint, bigint, string, string, string, string, bigint],
    undefined
  >,
  'createSubject' : ActorMethod<[bigint, string, string, string], undefined>,
  'generatePlaylistFromTelegram' : ActorMethod<
    [string, bigint, string],
    string
  >,
  'getChaptersBySubject' : ActorMethod<[bigint], Array<Chapter>>,
  'getItemsByPlaylist' : ActorMethod<[bigint], Array<PlaylistItem>>,
  'getPlaylistsByChapter' : ActorMethod<[bigint], Array<Playlist>>,
  'markItemStatus' : ActorMethod<[bigint, boolean], undefined>,
  'searchPlaylistsByName' : ActorMethod<[string], Array<Playlist>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];